/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.glb --root ../ -o ../../src/components/scene.glb.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/scene.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.立方体090.geometry} material={materials.材质} />
      <mesh geometry={nodes.立方体090_1.geometry} material={materials.黑色石质地面} />
      <mesh geometry={nodes.立方体090_2.geometry} material={materials.室内地毯} />
      <mesh geometry={nodes.立方体090_3.geometry} material={materials.电梯条纹} />
      <mesh geometry={nodes.立方体090_4.geometry} material={materials['磨砂玻璃门-中间不透']} />
      <mesh geometry={nodes.立方体090_5.geometry} material={materials['Material #72.002']} />
      <mesh geometry={nodes.立方体090_6.geometry} material={materials['材质.013']} />
      <mesh geometry={nodes.立方体090_7.geometry} material={materials['材质.003']} />
      <mesh geometry={nodes.立方体090_8.geometry} material={materials['keyboard_material.002']} />
      <mesh geometry={nodes.立方体090_9.geometry} material={materials['Keyboard_emit.002']} />
      <mesh geometry={nodes.立方体090_10.geometry} material={materials['柜子-红.001']} />
      <mesh geometry={nodes.立方体090_11.geometry} material={materials['Material #2142156146.001']} />
      <mesh geometry={nodes.立方体090_12.geometry} material={materials['显示器金属臂.001']} />
      <mesh geometry={nodes.立方体090_13.geometry} material={materials['logo墙.003']} />
      <mesh geometry={nodes.立方体090_14.geometry} material={materials['材质.008']} />
      <mesh geometry={nodes.立方体090_15.geometry} material={materials['材质.009']} />
      <mesh geometry={nodes.立方体090_16.geometry} material={materials['材质.012']} />
      <mesh geometry={nodes.立方体090_17.geometry} material={materials['柜子-白']} />
      <mesh geometry={nodes.立方体090_18.geometry} material={materials.塑料铭牌} />
      <mesh geometry={nodes.立方体090_19.geometry} material={materials[' 黑色塑料']} />
      <mesh geometry={nodes.立方体090_20.geometry} material={materials.锁芯} />
      <mesh geometry={nodes.立方体090_21.geometry} material={materials.密码锁} />
      <mesh geometry={nodes.立方体090_22.geometry} material={materials.白色塑料} />
      <mesh geometry={nodes.立方体090_23.geometry} material={materials['材质.026']} />
      <mesh geometry={nodes.立方体090_24.geometry} material={materials.开关} />
      <mesh geometry={nodes.立方体090_25.geometry} material={materials['材质.025']} />
      <mesh geometry={nodes.立方体090_26.geometry} material={materials.黑色金属} />
      <mesh geometry={nodes.立方体090_27.geometry} material={materials['小门右手墙面.001']} />
      <mesh geometry={nodes.立方体090_28.geometry} material={materials.白色微透塑料} />
      <mesh geometry={nodes.立方体090_29.geometry} material={materials.logo墙} />
      <mesh geometry={nodes.立方体090_30.geometry} material={materials.乐高桌面} />
      <mesh geometry={nodes.立方体090_31.geometry} material={materials['cedar wood']} />
      <mesh geometry={nodes.立方体090_32.geometry} material={materials['材质.038']} />
      <mesh geometry={nodes.立方体090_33.geometry} material={materials.玻璃门} />
      <mesh geometry={nodes.立方体090_34.geometry} material={materials.墙体金属包边} />
      <mesh geometry={nodes.立方体090_35.geometry} material={materials.空调液晶} />
      <mesh geometry={nodes.立方体090_36.geometry} material={materials.空调按键} />
      <mesh geometry={nodes.立方体090_37.geometry} material={materials['黑色玻璃-屏幕']} />
      <mesh geometry={nodes.立方体090_38.geometry} material={materials['雨伞架-塑料']} />
      <mesh geometry={nodes.立方体090_39.geometry} material={materials['柜子-灰']} />
      <mesh geometry={nodes.立方体090_40.geometry} material={materials['柜子-蓝']} />
      <mesh geometry={nodes.立方体090_41.geometry} material={materials.壁画} />
      <mesh geometry={nodes.立方体090_42.geometry} material={materials.普通开关} />
      <mesh geometry={nodes.立方体090_43.geometry} material={materials.先施公司照片} />
      <mesh geometry={nodes.立方体090_44.geometry} material={materials.普通拉门} />
      <mesh geometry={nodes.立方体090_45.geometry} material={materials['安全出口-绿色']} />
      <mesh geometry={nodes.立方体090_46.geometry} material={materials.银色包边} />
      <mesh geometry={nodes.立方体090_47.geometry} material={materials['black rubber']} />
      <mesh geometry={nodes.立方体090_48.geometry} material={materials['logo墙.001']} />
    </group>
  )
}

useGLTF.preload('/assets/scene.glb')
