/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 wall-roof.glb --root ../ -o ../../src/components/wall-roof.glb.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/wall-roof.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.天花板.geometry} material={nodes.天花板.material} position={[-6.006, 0.487, 2.7]} />
    </group>
  )
}

useGLTF.preload('/assets/wall-roof.glb')
